# Generated by Django 3.0.7 on 2020-06-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
